config/routes.rb
Rails.application.routes.draw do

  resources :groom_accessories
  resources :groom_suits
  resources :wedding_services
  resources :wedding_decorations
  resources :wedding_rooms
  resources :church_rings
  resources :church_bests
  resources :church_decorations
  resources :church_ceremonies
  resources :guests
  resources :bride_beauticans
  resources :bride_hairdressers
  resources :bride_accessories
  resources :bride_dresses
  root 'static_pages#index'

  get   'help'    => 'static_pages#help'
  get   'about'   => 'static_pages#about'
  get   'bride'   => 'static_pages#bride'
  get   'church'   => 'static_pages#church'
  get   'wedding'  => 'static_pages#wedding'
  get   'groom'    => 'static_pages#groom'
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  devise_for :users, controllers: {
             registrations: 'users/registrations',
             confirmations: 'users/confirmations',
             passwords: 'users/passwords',
             sessions: 'users/sessions',
             unlocks: 'users/unlocks'
           }
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride_accessory.rb
class BrideAccessory < ApplicationRecord
  belongs_to :user
end

app/models/bride_beautican.rb
class BrideBeautican < ApplicationRecord
  belongs_to :user
end

app/models/bride_dress.rb
class BrideDress < ApplicationRecord
  belongs_to :user
end

app/models/bride_hairdresser.rb
class BrideHairdresser < ApplicationRecord
  belongs_to :user
end

app/models/church_best.rb
class ChurchBest < ApplicationRecord
  belongs_to :user
end

app/models/church_ceremony.rb
class ChurchCeremony < ApplicationRecord
  belongs_to :user
end

app/models/church_decoration.rb
class ChurchDecoration < ApplicationRecord
  belongs_to :user
end

app/models/church_ring.rb
class ChurchRing < ApplicationRecord
  belongs_to :user
end

app/models/groom_accessory.rb
class GroomAccessory < ApplicationRecord
  belongs_to :user
end

app/models/groom_suit.rb
class GroomSuit < ApplicationRecord
  belongs_to :user
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :bride_dress
  has_one :groom_suit
  has_many :bride_accessories
  has_one :bride_beautican
  has_one :bride_hairdresser
  has_many :church_bests
  has_one :church_ceremony
  has_many :church_decorations
  has_many :church_rings
  has_many :groom_accessories
  has_many :guests
  has_many :wedding_decorations
  has_one :wedding_room
  has_many :wedding_services
end

app/models/wedding_decoration.rb
class WeddingDecoration < ApplicationRecord
  belongs_to :user
end

app/models/wedding_room.rb
class WeddingRoom < ApplicationRecord
  belongs_to :user
end

app/models/wedding_service.rb
class WeddingService < ApplicationRecord
  belongs_to :user
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "static", only: [:help, :about, :bride, :church, :wedding, :groom]
  def help
  end

  def about
  end

  def bride
    @bride_dresses = BrideDress.where(user_id: current_user.id)
    @bride_accessories = BrideAccessory.where(user_id: current_user.id)
    @bride_hairdressers = BrideHairdresser.where(user_id: current_user.id)
    @bride_beauticans = BrideBeautican.where(user_id: current_user.id)
  end

  def church
    @church_ceremonies = ChurchCeremony.where(user_id: current_user.id)
    @church_decorations = ChurchDecoration.where(user_id: current_user.id)
    @church_bests = ChurchBest.where(user_id: current_user.id)
    @church_rings = ChurchRing.where(user_id: current_user.id)
  end

  def wedding
    @wedding_rooms = WeddingRoom.where(user_id: current_user.id)
    @wedding_decorations = WeddingDecoration.where(user_id: current_user.id)
    @wedding_services = WeddingService.where(user_id: current_user.id)
  end

  def groom
    @groom_suits = GroomSuit.where(user_id: current_user.id)
    @groom_accessories = GroomAccessory.where(user_id: current_user.id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/church_bests_helper.rb
module ChurchBestsHelper
end

app/helpers/groom_suits_helper.rb
module GroomSuitsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<p>Ślub to wazne wydarzenie w naszym zyciu i kazdy chce, żeby byl on jak z bajki.
  Podczas organizacji potrzebne jest nam miejsce, gdzie zbierzemy wszystkie informacje.
  W dzisiejszych czasach zawsze mamy przy sobie telefon czy tablet z dostępem do internetu, dlatego tez
  posiadanie aplikacji jest wygodniejsze niz notesik czy organizer w formie tradycyjnej.
  Mamy wtedy pewność, że zawsze gdy przyjdzie potrzeba szybkiego zanotowania daty czy modelu butów,
  aplikacja jest w zasięgu naszej ręki - jest bardziej niezawodna niż zeszyt, który możemy zostawić w domu czy poplamić kawą.
  Ponadto używanie aplikacji pozwala nam na utrzymanie w notatkach porządku.
  Na każdą niezbędną informacje czeka wyznaczone miejsce. Nie marnujemy więc czasu na przeszukiwanie notesu kilka razy dziennie,
  by zaznaczyć, że kolejny z gości potwierdził nam swoją obecność w dniu ślubu</p>

app/views/static_pages/bride.html.erb
<h1>Panna młoda</h1>
<br><br>
<h3><i><b>Suknia ślubna</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Model</th>
      <th>Rozmiar</th>
      <th>Przymiarki</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bride_dresses.each do |bride_dress| %>
      <tr>
        <td><%= bride_dress.model %></td>
        <td><%= bride_dress.size %></td>
        <td><%= bride_dress.fitting %></td>
        <td><%= link_to 'Pokaż', bride_dress %></td>
        <td><%= link_to 'Edytuj', edit_bride_dress_path(bride_dress) %></td>
        <td><%= link_to 'Usuń', bride_dress, method: :delete, data: { confirm: 'Jesteś pewny/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj', new_bride_dress_path %>
<br><br>
<h3><i><b>Dodatki </i></b></h3>

<table class=table>
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Kolor</th>
      <th>Rozmiar</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bride_accessories.each do |bride_accessory| %>
      <tr>
        <td><%= bride_accessory.name %></td>
        <td><%= bride_accessory.color %></td>
        <td><%= bride_accessory.size %></td>
        <td><%= link_to 'Pokaż', bride_accessory %></td>
        <td><%= link_to 'Edytuj', edit_bride_accessory_path(bride_accessory) %></td>
        <td><%= link_to 'Usuń', bride_accessory, method: :delete, data: { confirm: 'Jesteś pewny/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj', new_bride_accessory_path %>
<br><br>
<h3><i><b>Fryzjer</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Wizyta próbna</th>
      <th>Wizyta w dniu ślubu</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bride_hairdressers.each do |bride_hairdresser| %>
      <tr>
        <td><%= bride_hairdresser.name %></td>
        <td><%= bride_hairdresser.fitting %></td>
        <td><%= bride_hairdresser.meeting %></td>
        <td><%= link_to 'Pokaż', bride_hairdresser %></td>
        <td><%= link_to 'Edytuj', edit_bride_hairdresser_path(bride_hairdresser) %></td>
        <td><%= link_to 'Usuń', bride_hairdresser, method: :delete, data: { confirm: 'Jesteś pewny/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj', new_bride_hairdresser_path %>
<br><br>
<h3><i><b>Kosmetyczka</b></i></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Wizyta próbna</th>
      <th>Wizyta w dniu ślubu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bride_beauticans.each do |bride_beautican| %>
      <tr>
        <td><%= bride_beautican.name %></td>
        <td><%= bride_beautican.fitting %></td>
        <td><%= bride_beautican.meeting %></td>
        <td><%= link_to 'Pokaż', bride_beautican %></td>
        <td><%= link_to 'Edytuj', edit_bride_beautican_path(bride_beautican) %></td>
        <td><%= link_to 'Usuń', bride_beautican, method: :delete, data: { confirm: 'Jesteś pewny/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Dodaj', new_bride_beautican_path %>

app/views/static_pages/church.html.erb
<h1>Kościół</h1>
<br><br>
<h3><i><b>Ceremonia</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Adres</th>
      <th>Data ceremonii</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @church_ceremonies.each do |church_ceremony| %>
      <tr>
        <td><%= church_ceremony.name %></td>
        <td><%= church_ceremony.adress %></td>
        <td><%= church_ceremony.date %></td>
        <td><%= link_to 'Pokaż', church_ceremony %></td>
        <td><%= link_to 'Edytuj', edit_church_ceremony_path(church_ceremony) %></td>
        <td><%= link_to 'Usuń', church_ceremony, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Dodaj', new_church_ceremony_path %>
<br><br>
<h3><i><b>Dodatki </i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Kolor</th>
      <th>Ilość</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @church_decorations.each do |church_decoration| %>
      <tr>
        <td><%= church_decoration.name %></td>
        <td><%= church_decoration.colour %></td>
        <td><%= church_decoration.amount %></td>
        <td><%= link_to 'Pokaż', church_decoration %></td>
        <td><%= link_to 'Edytuj', edit_church_decoration_path(church_decoration) %></td>
        <td><%= link_to 'Usuń', church_decoration, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj', new_church_decoration_path %>
<br><br>
<h3><i><b>Świadkowie</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @church_bests.each do |church_best| %>
      <tr>
        <td><%= church_best.name %></td>
        <td><%= church_best.surname %></td>
        <td><%= link_to 'Pokaż', church_best %></td>
        <td><%= link_to 'Edytuj', edit_church_best_path(church_best) %></td>
        <td><%= link_to 'Usuń', church_best, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj', new_church_best_path %>
<br><br>
<h3><i><b>Obrączki</b></i></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa modelu</th>
      <th>Rozmiar</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @church_rings.each do |church_ring| %>
      <tr>
        <td><%= church_ring.name %></td>
        <td><%= church_ring.size %></td>
        <td><%= link_to 'Pokaż', church_ring %></td>
        <td><%= link_to 'Edytuj', edit_church_ring_path(church_ring) %></td>
        <td><%= link_to 'Usuń', church_ring, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj', new_church_ring_path %>

app/views/static_pages/groom.html.erb
<h1>Pan Młody</h1>
<br><br>
<h3><i><b>Garnitur</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Model</th>
      <th>Rozmiar</th>
      <th>Przymiarka</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @groom_suits.each do |groom_suit| %>
      <tr>
        <td><%= groom_suit.model %></td>
        <td><%= groom_suit.size %></td>
        <td><%= groom_suit.fitting %></td>
        <td><%= link_to 'Pokaż', groom_suit %></td>
        <td><%= link_to 'Edytuj', edit_groom_suit_path(groom_suit) %></td>
        <td><%= link_to 'Usuń', groom_suit, method: :delete, data: { confirm: 'Jesteś pewny/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_groom_suit_path %>

<br><br>
<h3><i><b>Akcesoria</i></b></h3>
<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Kolor</th>
      <th>Rozmiar/Ilość</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @groom_accessories.each do |groom_accessory| %>
      <tr>
        <td><%= groom_accessory.name %></td>
        <td><%= groom_accessory.colour %></td>
        <td><%= groom_accessory.amount %></td>
        <td><%= link_to 'Pokaż', groom_accessory %></td>
        <td><%= link_to 'Edytuj', edit_groom_accessory_path(groom_accessory) %></td>
        <td><%= link_to 'Usuń', groom_accessory, method: :delete, data: { confirm: 'Jesteś pewny/a?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_groom_accessory_path %>

app/views/static_pages/help.html.erb
<h1>Pomoc</h1>

<p>Prosimy o napisanie maila do administracji na adres:</p>
<p>abruchwalska@sigma.ug.edu.pl</p>
<p>krostek@sigma.ug.edu.pl</p>

app/views/static_pages/index.html.erb
<% if user_signed_in? %>
  <div class="img-2">
    <div class="caption">
      <span class="border"><%= link_to "Panna młoda",   bride_path, class: 'link-text' %></span>
      <span class="border"><%= link_to "Pan młody",   groom_path, class: 'link-text' %></span>
    </div>
  </div>

  <div class="whiteb">
      <span class="border"><%= link_to "Goście",   guests_path, class: 'link-text' %></span>
  </div>

  <div class="img-3">
    <div class="caption">
      <span class="border"><%= link_to "Kościół ",   church_path, class: 'link-text' %></span>
      <span class="border"><%= link_to "Wesele",   wedding_path, class: 'link-text' %></span>
    </div>
  </div>
<% else %>
  <div class="img-1">
    <div class="caption">
      <span class="border">
        <%= link_to "Rejestracja", '/users/sign_up', class: 'link-text' %></span>
      <span class="border"><%= link_to "Logowanie", '/users/sign_in', class: 'link-text' %></span>
    </div>
  </div>
  <div class="whiteb">
    <span class="border-black"><i>Kocha się za nic. Nie is­tnieje żaden powód do miłości.
      <br>Paulo Coelho
    </i></span>
  </div>
<% end %>

app/views/static_pages/wedding.html.erb
<h1>Wesele</h1>
<br><br>
<h3><i><b>Sala Weselna</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa obiektu</th>
      <th>Adres</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @wedding_rooms.each do |wedding_room| %>
      <tr>
        <td><%= wedding_room.name %></td>
        <td><%= wedding_room.adress %></td>
        <td><%= link_to 'Pokaż', wedding_room %></td>
        <td><%= link_to 'Edytuj', edit_wedding_room_path(wedding_room) %></td>
        <td><%= link_to 'Usuń', wedding_room, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_wedding_room_path %>

<br><br>
<h3><i><b>Dekoracje </i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Kolor</th>
      <th>Ilość</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @wedding_decorations.each do |wedding_decoration| %>
      <tr>
        <td><%= wedding_decoration.name %></td>
        <td><%= wedding_decoration.colour %></td>
        <td><%= wedding_decoration.amount %></td>
        <td><%= link_to 'Pokaż', wedding_decoration %></td>
        <td><%= link_to 'Edytuj', edit_wedding_decoration_path(wedding_decoration) %></td>
        <td><%= link_to 'Usuń', wedding_decoration, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_wedding_decoration_path %>

<br><br>
<h3><i><b>Obsługa</i></b></h3>

<table class="table">
  <thead>
    <tr>
      <th>Kto</th>
      <th>Nazwa</th>
      <th>Kontakt</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @wedding_services.each do |wedding_service| %>
      <tr>
        <td><%= wedding_service.who %></td>
        <td><%= wedding_service.name %></td>
        <td><%= wedding_service.contact %></td>
        <td><%= link_to 'Pokaż', wedding_service %></td>
        <td><%= link_to 'Edytuj', edit_wedding_service_path(wedding_service) %></td>
        <td><%= link_to 'Usuń', wedding_service, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_wedding_service_path %>