config/routes.rb
Rails.application.routes.draw do

  resources :groom_accessories
  resources :groom_suits
  resources :wedding_services
  resources :wedding_decorations
  resources :wedding_rooms
  resources :church_rings
  resources :church_bests
  resources :church_decorations
  resources :church_ceremonies
  resources :guests
  resources :bride_beauticans
  resources :bride_hairdressers
  resources :bride_accessories
  resources :bride_dresses
  root 'static_pages#index'

  get   'help'    => 'static_pages#help'
  get   'about'   => 'static_pages#about'
  get   'bride'   => 'static_pages#bride'
  get   'church'   => 'static_pages#church'
  get   'wedding'  => 'static_pages#wedding'
  get   'groom'    => 'static_pages#groom'
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  devise_for :users, controllers: {
             registrations: 'users/registrations',
             confirmations: 'users/confirmations',
             passwords: 'users/passwords',
             sessions: 'users/sessions',
             unlocks: 'users/unlocks'
           }
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride_accessory.rb
class BrideAccessory < ApplicationRecord
  belongs_to :user
end

app/models/bride_beautican.rb
class BrideBeautican < ApplicationRecord
  belongs_to :user
end

app/models/bride_dress.rb
class BrideDress < ApplicationRecord
  belongs_to :user
end

app/models/bride_hairdresser.rb
class BrideHairdresser < ApplicationRecord
  belongs_to :user
end

app/models/church_best.rb
class ChurchBest < ApplicationRecord
  belongs_to :user
end

app/models/church_ceremony.rb
class ChurchCeremony < ApplicationRecord
  belongs_to :user
end

app/models/church_decoration.rb
class ChurchDecoration < ApplicationRecord
  belongs_to :user
end

app/models/church_ring.rb
class ChurchRing < ApplicationRecord
  belongs_to :user
end

app/models/groom_accessory.rb
class GroomAccessory < ApplicationRecord
  belongs_to :user
end

app/models/groom_suit.rb
class GroomSuit < ApplicationRecord
  belongs_to :user
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :bride_dress
  has_one :groom_suit
  has_many :bride_accessories
  has_one :bride_beautican
  has_one :bride_hairdresser
  has_many :church_bests
  has_one :church_ceremony
  has_many :church_decorations
  has_many :church_rings
  has_many :groom_accessories
  has_many :guests
  has_many :wedding_decorations
  has_one :wedding_room
  has_many :wedding_services
end

app/models/wedding_decoration.rb
class WeddingDecoration < ApplicationRecord
  belongs_to :user
end

app/models/wedding_room.rb
class WeddingRoom < ApplicationRecord
  belongs_to :user
end

app/models/wedding_service.rb
class WeddingService < ApplicationRecord
  belongs_to :user
end

app/controllers/wedding_rooms_controller.rb
class WeddingRoomsController < ApplicationController
  layout "static"
  before_action :set_wedding_room, only: [:show, :edit, :update, :destroy]

  # GET /wedding_rooms
  # GET /wedding_rooms.json
  def index
    @wedding_rooms = WeddingRoom.all
  end

  # GET /wedding_rooms/1
  # GET /wedding_rooms/1.json
  def show
  end

  # GET /wedding_rooms/new
  def new
    @wedding_room = WeddingRoom.new
  end

  # GET /wedding_rooms/1/edit
  def edit
  end

  # POST /wedding_rooms
  # POST /wedding_rooms.json
  def create
    @wedding_room = WeddingRoom.new(wedding_room_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @wedding_room.save
        format.html { redirect_to @wedding_room, notice: 'Dane sali zostały dodane.' }
        format.json { render :show, status: :created, location: @wedding_room }
      else
        format.html { render :new }
        format.json { render json: @wedding_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wedding_rooms/1
  # PATCH/PUT /wedding_rooms/1.json
  def update
    respond_to do |format|
      if @wedding_room.update(wedding_room_params)
        format.html { redirect_to @wedding_room, notice: 'Dane sali zostały edytowane.' }
        format.json { render :show, status: :ok, location: @wedding_room }
      else
        format.html { render :edit }
        format.json { render json: @wedding_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wedding_rooms/1
  # DELETE /wedding_rooms/1.json
  def destroy
    @wedding_room.destroy
    respond_to do |format|
      format.html { redirect_to wedding_rooms_url, notice: 'Dane sali zostały usunięte.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wedding_room
      @wedding_room = WeddingRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wedding_room_params
      params.require(:wedding_room).permit(:name, :adress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/church_bests_helper.rb
module ChurchBestsHelper
end

app/helpers/church_rings_helper.rb
module ChurchRingsHelper
end

app/helpers/groom_suits_helper.rb
module GroomSuitsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/wedding_rooms_helper.rb
module WeddingRoomsHelper
end

app/views/wedding_rooms/_form.html.erb
<%= form_for(wedding_room) do |f| %>
  <% if wedding_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wedding_room.errors.count, "error") %>Nie można dodać elementu</h2>

      <ul>
      <% wedding_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name , 'Nazwa obiektu'%>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :adress, 'Adres' %>
    <%= f.text_area :adress %>
  </div>

  <div class="actions">
    <%= f.submit 'Potwierdź'%>
  </div>
<% end %>

app/views/wedding_rooms/edit.html.erb
<h1>Edytuj Sale Weselna</h1>

<%= render 'form', wedding_room: @wedding_room %>

<%= link_to 'Pokaż', @wedding_room %> |
<%= link_to 'Wróć', wedding_rooms_path %>

app/views/wedding_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sala Weselna</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa obiektu</th>
      <th>Adres</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @wedding_rooms.each do |wedding_room| %>
      <tr>
        <td><%= wedding_room.name %></td>
        <td><%= wedding_room.adress %></td>
        <td><%= link_to 'Pokaż', wedding_room %></td>
        <td><%= link_to 'Edytuj', edit_wedding_room_path(wedding_room) %></td>
        <td><%= link_to 'Usuń', wedding_room, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_wedding_room_path %>|
<%= link_to 'Wroc', wedding_path %>

app/views/wedding_rooms/new.html.erb
<h1>Nowa Sala Weselna</h1>

<%= render 'form', wedding_room: @wedding_room %>

<%= link_to 'Wróć', wedding_rooms_path %>

app/views/wedding_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa obiektu:</strong>
  <%= @wedding_room.name %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @wedding_room.adress %>
</p>

<%= link_to 'Edytuj', edit_wedding_room_path(@wedding_room) %> |
<%= link_to 'Wróć', wedding_rooms_path %>