config/routes.rb
Rails.application.routes.draw do

  resources :groom_accessories
  resources :groom_suits
  resources :wedding_services
  resources :wedding_decorations
  resources :wedding_rooms
  resources :church_rings
  resources :church_bests
  resources :church_decorations
  resources :church_ceremonies
  resources :guests
  resources :bride_beauticans
  resources :bride_hairdressers
  resources :bride_accessories
  resources :bride_dresses
  root 'static_pages#index'

  get   'help'    => 'static_pages#help'
  get   'about'   => 'static_pages#about'
  get   'bride'   => 'static_pages#bride'
  get   'church'   => 'static_pages#church'
  get   'wedding'  => 'static_pages#wedding'
  get   'groom'    => 'static_pages#groom'
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end

  devise_for :users, controllers: {
             registrations: 'users/registrations',
             confirmations: 'users/confirmations',
             passwords: 'users/passwords',
             sessions: 'users/sessions',
             unlocks: 'users/unlocks'
           }
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bride_accessory.rb
class BrideAccessory < ApplicationRecord
  belongs_to :user
end

app/models/bride_beautican.rb
class BrideBeautican < ApplicationRecord
  belongs_to :user
end

app/models/bride_dress.rb
class BrideDress < ApplicationRecord
  belongs_to :user
end

app/models/bride_hairdresser.rb
class BrideHairdresser < ApplicationRecord
  belongs_to :user
end

app/models/church_best.rb
class ChurchBest < ApplicationRecord
  belongs_to :user
end

app/models/church_ceremony.rb
class ChurchCeremony < ApplicationRecord
  belongs_to :user
end

app/models/church_decoration.rb
class ChurchDecoration < ApplicationRecord
  belongs_to :user
end

app/models/church_ring.rb
class ChurchRing < ApplicationRecord
  belongs_to :user
end

app/models/groom_accessory.rb
class GroomAccessory < ApplicationRecord
  belongs_to :user
end

app/models/groom_suit.rb
class GroomSuit < ApplicationRecord
  belongs_to :user
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :bride_dress
  has_one :groom_suit
  has_many :bride_accessories
  has_one :bride_beautican
  has_one :bride_hairdresser
  has_many :church_bests
  has_one :church_ceremony
  has_many :church_decorations
  has_many :church_rings
  has_many :groom_accessories
  has_many :guests
  has_many :wedding_decorations
  has_one :wedding_room
  has_many :wedding_services
end

app/models/wedding_decoration.rb
class WeddingDecoration < ApplicationRecord
  belongs_to :user
end

app/models/wedding_room.rb
class WeddingRoom < ApplicationRecord
  belongs_to :user
end

app/models/wedding_service.rb
class WeddingService < ApplicationRecord
  belongs_to :user
end

app/controllers/church_ceremonies_controller.rb
class ChurchCeremoniesController < ApplicationController
  layout "static"
  before_action :set_church_ceremony, only: [:show, :edit, :update, :destroy]

  # GET /church_ceremonies
  # GET /church_ceremonies.json
  def index
    @church_ceremonies = ChurchCeremony.all
  end

  # GET /church_ceremonies/1
  # GET /church_ceremonies/1.json
  def show
  end

  # GET /church_ceremonies/new
  def new
    @church_ceremony = ChurchCeremony.new
  end

  # GET /church_ceremonies/1/edit
  def edit
  end

  # POST /church_ceremonies
  # POST /church_ceremonies.json
  def create
    @church_ceremony = ChurchCeremony.new(church_ceremony_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @church_ceremony.save
        format.html { redirect_to @church_ceremony, notice: 'Dane ceremonii zostały dodane.' }
        format.json { render :show, status: :created, location: @church_ceremony }
      else
        format.html { render :new }
        format.json { render json: @church_ceremony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /church_ceremonies/1
  # PATCH/PUT /church_ceremonies/1.json
  def update
    respond_to do |format|
      if @church_ceremony.update(church_ceremony_params)
        format.html { redirect_to @church_ceremony, notice: 'Dane ceremonii zostały edytowane.' }
        format.json { render :show, status: :ok, location: @church_ceremony }
      else
        format.html { render :edit }
        format.json { render json: @church_ceremony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /church_ceremonies/1
  # DELETE /church_ceremonies/1.json
  def destroy
    @church_ceremony.destroy
    respond_to do |format|
      format.html { redirect_to church_ceremonies_url, notice: 'Dane ceremonii zostały usunięte.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_church_ceremony
      @church_ceremony = ChurchCeremony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def church_ceremony_params
      params.require(:church_ceremony).permit(:name, :adress, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/church_bests_helper.rb
module ChurchBestsHelper
end

app/helpers/church_ceremonies_helper.rb
module ChurchCeremoniesHelper
end

app/helpers/church_rings_helper.rb
module ChurchRingsHelper
end

app/helpers/groom_suits_helper.rb
module GroomSuitsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/church_ceremonies/_form.html.erb
<%= form_for(church_ceremony) do |f| %>
  <% if church_ceremony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(church_ceremony.errors.count, "error") %> Nie można dodać elementu</h2>

      <ul>
      <% church_ceremony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nazwa' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :adress, 'Adres' %>
    <%= f.text_area :adress %>
  </div>

  <div class="field">
    <%= f.label :date, 'Data' %>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit 'Potwierdź' %>
  </div>
<% end %>

app/views/church_ceremonies/edit.html.erb
<h1>Edytuj ceremonie</h1>

<%= render 'form', church_ceremony: @church_ceremony %>

<%= link_to 'Pokaż', @church_ceremony %> |
<%= link_to 'Wróć', church_ceremonies_path %>

app/views/church_ceremonies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ceremonia</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Adres</th>
      <th>Data ceremonii</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @church_ceremonies.each do |church_ceremony| %>
      <tr>
        <td><%= church_ceremony.name %></td>
        <td><%= church_ceremony.adress %></td>
        <td><%= church_ceremony.date %></td>
        <td><%= link_to 'Pokaż', church_ceremony %></td>
        <td><%= link_to 'Edytuj', edit_church_ceremony_path(church_ceremony) %></td>
        <td><%= link_to 'Usuń', church_ceremony, method: :delete, data: { confirm: 'Jesteś pewny/a' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj', new_church_ceremony_path %> |
<%= link_to 'Wróć', church_path %>

app/views/church_ceremonies/new.html.erb
<h1>Nowa Ceremonia</h1>

<%= render 'form', church_ceremony: @church_ceremony %>

<%= link_to 'Wróć', church_ceremonies_path %>

app/views/church_ceremonies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @church_ceremony.name %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @church_ceremony.adress %>
</p>

<p>
  <strong>Data:</strong>
  <%= @church_ceremony.date %>
</p>

<%= link_to 'Edytuj', edit_church_ceremony_path(@church_ceremony) %> |
<%= link_to 'Wróć', church_ceremonies_path %>